services:
  tour:
    build: 
      context: .
      dockerfile: play.Dockerfile
  docs:
    environment:
      - GOROOT=/usr/local/go
    build: 
      context: .
      dockerfile: pkg.Dockerfile
  
  nginx:
   image: nginx:alpine
   restart: always
   volumes:
     - ./nginx:/etc/nginx/conf.d
   ports:
     - 8080:80
