services:
  tour:
    build: 
      context: .
      dockerfile: Dockerfile
  
  nginx:
   image: nginx:alpine
   restart: always
   volumes:
     - ./nginx:/etc/nginx/conf.d
   ports:
     - 8080:80
